### ISSUE TITLE
WHATTT?????

### ISSUE THREAD

**Issue by elzershark** [whitebird/mqtt-ambilight#1]
Copy configuration.example.yaml to configuration.example.yaml and add your mqtt details.

What??????

Copy a file to a file ?????????

docker run -it \
    -v ~/mqtt-ambilight/configuration.yaml...."WHATTTT????":/configuration.yaml  WHATTT????\
    --device=/dev/video0:/dev/video0 \
    --net="host"WHATTT???? \
    -t mqtt-ambilightWHATTT????

What the f....????
You are Drunk????

**Comment by DrSkunk** [comment]
Hi, what's not clear about the instructions? I'm afraid I don't respond well to this kind of language though. Can you try again?

**Comment by elzershark** [comment]
Then install that according to the instructions. That cannot work at all. There is something wrong with everything.

**Comment by elzershark** [comment]
docker run -it \
    -v ~/mqtt-ambilight/configuration.yaml:/configuration.yaml \
    --device=/dev/video0:/dev/video0 \
    --net="host" \
    -t mqtt-ambilight


These files do not exist:
mqtt-ambilight
configuration.yaml


I've already read some instructions. But this is awesome. Incomprehensible

**Comment by DrSkunk** [comment]
Please read the instructions on Docker run: https://docs.docker.com/engine/reference/run/
You'll see what you did wrong. I will close this topic because you're not able to ask nicely.

I made this software free and opensource and developed it in my free time. All I ask is a little bit of respect and you're not able to provide it.

Have a nice day.
